---
- name: my_job1
  command: df -k /home
  timeout: 5
  max_attempts: 10
  cadence_multiplier: 2      # everytime the process fails run again cadence*candance_multiplier later
  when:
    cadence: 10
    unit: seconds
    cron: "45 17 */2  * *"   # either specify a cadence or specify a cron like entry

- name: my_job2
  command: /path/to/some/foo/script/bar.sh
  chdir: /path/to/dir/to/exec/command/in
  args:
    arg1
    arg2
  transforms:
    - module.function1
    - module.function2
    - module.function3
