---
stages:
  - disks
  - nfs
  - ceph


.disk_usage_base:
  stage: disks
  timeout:
    duration: 5s
    max_attempts: 10
  when:
    interval: 10s
    cadence_multiplier: 2


.disk_usage_kb:
  extends: .disk_usage_base
  nlogn.builtin.command:
    cmd: df -bk $MOUNT_POINT
  output:
    transform:
      - nlogn.builtin.remove_header:
          - first_line
    columns:
      - filesystem[str]
      - mount_point[str]
      - bytes_total[long:kB]
      - bytes_used[long:kB]
    target: 'name of table or index in es'
    unit: kb


.disk_usage_inodes:
  extends: .disk_usage_base
  nlogn.builtin.command:
    cmd: df -i $MOUNT_POINT
  transform:
    nlogn.builtin.df_command:
      output_columns:
        - filesystem[str]
        - mount_point[str]
        - inodes_total[long]
        - inodes_used[long]


root_part_usage:
  extends: .disk_usage_kb
  variables:
    MOUNT_POINT: /root


root_part_usage_inodes:
  extends: .disk_usage_inodes
  variables:
    MOUNT_POINT: /root


shm_part_usage:
  extends: .disk_usage_kb
  variables:
    MOUNT_POINT: /dev/shm


shm_part_usage_inodes:
  extends: .disk_usage_inodes
  variables:
    MOUNT_POINT: /dev/shm


.nfs_usage_base:
  stage: nfs
  timeout:
    duration: 5s
    max_attempts: 10
  when:
    interval: 10s
    cadence_multiplier: 2


.nfs_usage_kb:
  extends: .nfs_usage_base
  nlogn.builtin.command:
    cmd: df -bk $MOUNT_POINT
  output:
    transform:
      - nlogn.builtin.remove_header:
        - first_line
    columns:
      - filesystem[str]
      - mount_point[str]
      - bytes_total[long:kB]
      - bytes_used[long:kB]
    target: 'name of table or index in es'

.nfs_usage_inodes:
  extends: .nfs_usage_base
  nlogn.builtin.command:
    cmd: df -i $MOUNT_POINT
  transform:
    nlogn.builtin.df_command:
      output_columns:
        - filesystem[str]
        - mount_point[str]
        - inodes_total[long]
        - inodes_used[long]
      unit: kb

home_part_usage:
  extends: .nfs_usage_kb
  variables:
    MOUNT_POINT: /home
...