---
stages:
  - disks
  - nfs
  - ceph


.disk_usage_base:
  stage: disks
  timeout:
    duration: 2s
    max_attempts: 5
  when:
    interval: 5s
    cadence_multiplier: 2


.disk_usage:
  extends: .disk_usage_base
  nlogn.builtin.command:
    cmd: df -Bk $MOUNT_POINT
  output:
    transform:
      - nlogn.builtin.utils.df_cmd_size_single_mount:
    columns:
      - filesystem[keyword]
      - mount[keyword]
      - size_total[long:KB]
      - size_used[long:KB]
    target: 'name of table or index in es'

.disk_usage_inodes:
  extends: .disk_usage_base
  nlogn.builtin.command:
    cmd: df -i $MOUNT_POINT
  output:
    transform:
      - nlogn.builtin.utils.df_cmd_inodes_single_mount:
    columns:
      - filesystem[keyword]
      - mount[keyword]
      - inodes_total[long]
      - inodes_used[long]
    target: 'name of table or index in es'


root_part_usage:
  extends: .disk_usage
  variables:
    MOUNT_POINT: /root


root_part_usage_inodes:
  extends: .disk_usage_inodes
  variables:
    MOUNT_POINT: /root


shm_part_usage:
  extends: .disk_usage
  variables:
    MOUNT_POINT: /dev/shm


shm_part_usage_inodes:
  extends: .disk_usage_inodes
  variables:
    MOUNT_POINT: /dev/shm


.nfs_usage_base:
  stage: nfs
  timeout:
    duration: 5s
    max_attempts: 3
  when:
    interval: 120s
    cadence_multiplier: 2


.nfs_usage:
  extends: .nfs_usage_base
  nlogn.builtin.command:
    cmd: df -Bk $MOUNT_POINT
  output:
    transform:
      - nlogn.builtin.utils.df_cmd_size_single_mount:
    columns:
      - filesystem[keyword]
      - mount[keyword]
      - size_total[long:KB]
      - size_used[long:KB]
    target: 'name of table or index in es'

.nfs_usage_inodes:
  extends: .nfs_usage_base
  nlogn.builtin.command:
    cmd: df -i $MOUNT_POINT
  output:
    transform:
      - nlogn.builtin.utils.df_cmd_inodes_single_mount:
    columns:
      - filesystem[str]
      - mount[str]
      - inodes_total[long]
      - inodes_used[long]
    target: 'name of table or index in es'


home_part_usage:
  extends: .nfs_usage
  variables:
    MOUNT_POINT: /home
...