package = 'nlogn'
project = 'nlogn'
project_no_spaces = project.replace(' ', '')
version = '0.0.0.dev0'
description = 'flexible, decentralized logging facility'
authors = ['Mher Kazandjian']
authors_string = ', '.join(authors)
emails = ['mherkazandjian@gmail.com']
license = 'GPL v3'
copyright = '2022 ' + authors_string
url = 'https://github.com/mherkazandjian/nlogn'